# Generated by Django 5.2.5 on 2025-10-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_cuentapago_planrestaurante_solicitudrestaurante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plato',
            options={},
        ),
        migrations.AddField(
            model_name='plato',
            name='contiene_azucar',
            field=models.BooleanField(default=True, help_text='Contiene azúcar'),
        ),
        migrations.AddField(
            model_name='plato',
            name='contiene_hielo',
            field=models.BooleanField(default=True, help_text='Sirve con hielo'),
        ),
        migrations.AddField(
            model_name='plato',
            name='es_caliente',
            field=models.BooleanField(default=False, help_text='Para café/té caliente'),
        ),
        migrations.AddField(
            model_name='plato',
            name='grados_alcohol',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Graduación alcohólica', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='tipo_bebida',
            field=models.CharField(blank=True, choices=[('REFRESCO', 'Refresco'), ('ALCOHOLICA', 'Bebida Alcohólica'), ('JUGOS', 'Jugos Naturales'), ('CAFE', 'Café y Té'), ('SMOOTHIE', 'Smoothies'), ('AGUA', 'Agua y Bebidas')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='volumen_ml',
            field=models.IntegerField(blank=True, help_text='Volumen en mililitros', null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='tiempo_preparacion',
            field=models.IntegerField(default=5, help_text='Tiempo en minutos'),
        ),
    ]
